### PR TITLE
More parsed personal player information

### PR DESCRIPTION
**Pull request by dounai2333**
:P

### CODE REVIEW

**Comment by Ochii** [comment]
Well done
I don't understand how avatars and achievements work, and what is a 'personal signature'?

I should merge this soon after testing. Do you want to add these new properties to the [database as well](https://github.com/Ochii/cso2-users-service)?

**Comment by dounai2333** [comment]
> Well done
> I don't understand how avatars and achievements work, and what is a 'personal signature'?
> 
> I should merge this soon after testing. Do you want to add these new properties to the [database as well](https://github.com/Ochii/cso2-users-service)?

if you're talking about achievements like CS:S, I never found any clue about this things
about player's avatar, title (serious, I also think this translate is little inappropriate, so I have thought of many words to express it, but... that's really what it's called
QNQH6O}$K_HOQFTYHAF}K75
O%P42P~VYNUI~VXW%KS N$Q
) and personal signature actually the person who made it was @CCasusensa, and I just did a little bit of work, like find out where it was saved, when i'm writing these words, I got his permission to publish these things, so I'll post it at the end.
about the personal signature, my expression may not be so good, so check the picture below:






about the database update, I'm not sure what part you want... because some of them seems useless, so I think still need you to complete this


serverinstance:
`--
            case PacketId.Aboutme:
                return this.users.onAboutmePacket(packet.getData(), sourceSocket)`

packets\achieshared: (new file)
`export enum AboutmePacketType {
    SetMessage = 5,
    SetTitle = 6,
    SetAchIcon = 7,
}
`

definitions:
`--
    Aboutme = 69,`

usermanager:
`--
import { AboutmePacketType } from 'packets/achieshared'
import { InAboutmePacket } from 'packets/in/aboutme'
import { InAboutmeSetIcon } from 'packets/in/aboutme/seticon'
import { InAboutmeSetMessage } from 'packets/in/aboutme/setmessage'
import { InAboutmeSetTitle } from 'packets/in/aboutme/settitle'
--
    public onAboutmePacket(AboutmeData: Buffer, sourceSocket: ExtendedSocket): boolean {
        const achPacket: InAboutmePacket = new InAboutmePacket(AboutmeData)
        const user: User = this.getUserByUuid(sourceSocket.uuid)

        if (user == null) {
            console.warn('Uuid %s sent a Aboutme packet without login', sourceSocket.uuid)
            return false
        }

        switch (achPacket.packetType) {
            case AboutmePacketType.SetMessage:
                const messageData: InAboutmeSetMessage = new InAboutmeSetMessage(achPacket)
                return this.onAboutmeSetMessage(messageData, user)
            case AboutmePacketType.SetTitle:
                const titleData: InAboutmeSetTitle = new InAboutmeSetTitle(achPacket)
                return this.onAboutmeSetTitle(titleData, user)
            case AboutmePacketType.SetAchIcon:
                const achiconData: InAboutmeSetIcon = new InAboutmeSetIcon(achPacket)
                return this.onAboutmeSetIcon(achiconData, user)
            default:
                console.warn('UserManager::onAboutmePacket: unknown packet type %i', achPacket.packetType)
        }

        return true
    }

    public onAboutmeSetMessage(messageData: InAboutmeSetMessage, user: User): boolean {
        const message: string = messageData.message
        // user.inventory.setAboutmeMessage(message)
        const updateMessage: Buffer = new OutUserInfoPacket(user.socket).fullUserUpdate(user)
        user.socket.send(updateMessage)
        console.log('Setting user "%s"\'s aboutme message %s', user.userName, message)
        return true
    }

    public onAboutmeSetTitle(titleData: InAboutmeSetTitle, user: User): boolean {
        const title: number = titleData.title
        // user.inventory.setTitle(title)
        const updateMessage: Buffer = new OutUserInfoPacket(user.socket).fullUserUpdate(user)
        user.socket.send(updateMessage)
        console.log('Setting user "%s"\'s aboutme title %s', user.userName, title)
        return true
    }

    public onAboutmeSetIcon(IconData: InAboutmeSetIcon, user: User): boolean {
        const icon: number = IconData.icon
        // user.inventory.setIcon(icon)
        const updateMessage: Buffer = new OutUserInfoPacket(user.socket).fullUserUpdate(user)
        user.socket.send(updateMessage)
        console.log('Setting user "%s"\'s aboutme icon %s', user.userName, icon)
        return true
    }`

packets\in\aboutme: (new file)
`import { InPacketBase } from 'packets/in/packet'

import { AboutmePacketType } from 'packets/achieshared'

/**
 * incoming Aboutme packet
 * @class InAboutmePacket
 */
export class InAboutmePacket extends InPacketBase {
    public packetType: AboutmePacketType

    /**
     * parses the packet's data
     */
    protected parse(): void {
        super.parse()

        this.packetType = this.readUInt8()
    }
}
`

packets\in\aboutme\seticon: (new file)
`import { InPacketBase } from 'packets/in/packet'

/**
 * requests an user's setting aboutme icon
 * @class InHostSetAboutmeIcon
 */

export class InAboutmeSetIcon {
    public icon: number

    constructor(inPakcet: InPacketBase) {
        this.icon = inPakcet.readUInt16()
    }
}
`
and setmessage, settitle use a same but little different words:
setmessage: read string, settitle: same with seticon except name.

user.inventory is a standalone update from us, so I annotated it, I did not had much experience with TS and JS, you should have notice it when I first time do PR, I even modifie the file multiple times just because of the weird space requirement of TS... sorry I can't help much about this...... :(

**Comment by Ochii** [comment]
@dounai2333 Do you want to commit the packet definitions?

@CCasusensa do you want to co-author these commits with @dounai2333? If so post your email (or the no-reply email assigned to your account).

**Comment by dounai2333** [comment]
I've already posted it... "--" is an omission, because those are irrelevant ahh whatever

```
--
Host = 68,
Aboutme = 69,
Udp = 70,
```

branch packets type (packets\achieshared):
```
export enum AboutmePacketType {
    SetMessage = 5,
    SetTitle = 6,
    SetAchIcon = 7,
}
```

**Pull request merged**
